setTagToTagGroup({
    "Surgery": "Treatments",
    "Chemo": "Treatments",
    "Radiation": "Treatments",
    "Chemoembolization / T.A.C.E": "Treatments",
    "Radioembolization": "Treatments",
    "Ethanol Embolization": "Treatments",
    "Embolization": "Treatments",
    "Immunotherapy": "Treatments",
    "Bone Marrow Transplantation": "Treatments",
    "Alternative Therapy": "Treatments",
    "Clinical Trials": "Treatments",
    "Nutrition": "General Knowledge and Tips",
    "Exercise": "General Knowledge and Tips",
    "Emotional Support": "General Knowledge and Tips",
    "Caring for Someone Fighting Fibrolamellar": "General Knowledge and Tips",
    "Comforting Someone After the Loss of a Loved One": "General Knowledge and Tips",
    "Doing Your Own Research on Fibrolamellar": "General Knowledge and Tips",
    "Advocating for Yourself or a Loved One": "General Knowledge and Tips",
    "\"5FU\"/Fluorouracil + \"Intron\"/Interferon Alpha": "Chemotherapy",
    "\"5FU\"/Fluorouracil + \"Eloxatin\"/Oxaliplatin": "Chemotherapy",
    "\"5FU\"/Fluorouracil ": "Chemotherapy",
    "\"Nexavar\"/Sorafenib + \"Avastin\"/Bevacizumab": "Chemotherapy",
    "\"Nexavar\"/Sorafenib": "Chemotherapy",
    "\"Xeloda\"/Capecitabine": "Chemotherapy",
    "\"Platinol\"/Cisplatin": "Chemotherapy",
    "\"Sutent\"/Sunitinib": "Chemotherapy",
    "\"AVATAR\" (\"Avastin\"/Bevacizumab + \"Tarceva\"/Erlotinib)": "Chemotherapy",
    "\"Tarceva\"/Erlotinib": "Chemotherapy",
    "\"GEMOX\" (\"Gemzar\"/Gemcitabine + \"Eloxatin\"/Oxaliplatin)": "Chemotherapy",
    "\"Gemzar\"/Gemcitabine + \"Eloxatin\"/Oxaliplatin + \"Avastin\"/Bevacizumab": "Chemotherapy",
    "\"Gemzar\"/Gemcitabine": "Chemotherapy",
    "\"Adriamycin\"/Doxorubicin + \"Platinol\"/Cisplatin": "Chemotherapy",
    "\"Adriamycin\"/\"Doxil\"/Doxorubicin": "Chemotherapy",
    "\"Affinitor\"/Everolimus": "Chemotherapy",
    "PIAF - Platinum Interferon Adriamycin Fluorouracil": "Chemotherapy",
    "\"Avastin\"/Bevacizumab": "Chemotherapy",
    "Linifanib": "Chemotherapy",
    "\"Camptosar\"/Irinotecan": "Chemotherapy",
    "\"Oncovin\"/Vincristine": "Chemotherapy",
    "Mouth Sores": "Symptoms and Side Effects",
    "Nausea": "Symptoms and Side Effects",
    "Fatigue": "Symptoms and Side Effects",
    "Loss of Appetite": "Symptoms and Side Effects",
    "Problems with Hands and Feet": "Symptoms and Side Effects",
    "Jaundice (yellowing of skin or eyes)": "Symptoms and Side Effects",
    "Abdominal Pain": "Symptoms and Side Effects",
    "Ache and Pains": "Symptoms and Side Effects",
    "Neuropathy (loss of feeling in fingers or toes)": "Symptoms and Side Effects",
    "Thrush (white tongue)": "Symptoms and Side Effects",
    "Blood Clots": "Symptoms and Side Effects",
    "Lymphedema (Swelling)": "Symptoms and Side Effects",
    "Changes in Sense of Taste (e.g. a metal taste in your mouth)": "Symptoms and Side Effects",
    "High Ammonia Levels": "Symptoms and Side Effects",
    "Managing Catheters/Drains": "Symptoms and Side Effects",
    "Ascites": "Symptoms and Side Effects",
    "Abscess": "Symptoms and Side Effects",
    "Weight Loss": "Symptoms and Side Effects",
    "Weight Gain": "Symptoms and Side Effects",
    "Bowel Obstruction": "Symptoms and Side Effects",
    "Fever": "Symptoms and Side Effects",
    "Diarrhea": "Symptoms and Side Effects",
    "Rashes": "Symptoms and Side Effects",
    "Itchiness": "Symptoms and Side Effects",
    "Hair Loss": "Symptoms and Side Effects",
    "Vomiting": "Symptoms and Side Effects",
    "Low Blood Cell Counts (Neutropenia, Anemia)": "Symptoms and Side Effects",
    "Heartburn": "Symptoms and Side Effects",
    "Black Stools": "Symptoms and Side Effects",
    "External Beam/Proton Radiation": "Radiation",
    "Y90/Sirspheres/Therospheres - Radioactive Beads": "Radiation",
    "RFA (Radiofrequency Ablation)": "Radiation",
    "Cyberknife": "Radiation",
    "Brachytherapy": "Radiation",
    "Liver Surgery": "Surgery",
    "Liver Transplantation": "Surgery",
    "Surgery to Remove Tumors Outside of the Liver": "Surgery",
    "Laproscopic or Minimally Invasive Surgery": "Surgery",
    "Laser Surgery": "Surgery",
    "Recurrence": "Disease Stage",
    "Inspiration": "General Knowledge and Tips",
    "Advocacy": "General Knowledge and Tips",
    "Metastases": "Disease Stage",
    "No Disease Outside the Liver": "Disease Stage",
    "Second Opinions": "General Knowledge and Tips",
    "Cysts": "General Knowledge and Tips",
    "Paracentesis": "General Knowledge and Tips",
    "Diuretics": "General Knowledge and Tips",
    "Infection": "Symptoms and Side Effects",
    "Edema": "Symptoms and Side Effects",
    "Lasix": "General Knowledge and Tips",
    "Compression Socks": "General Knowledge and Tips",
    "Albumin": "General Knowledge and Tips",
    "Low Sodium": "Symptoms and Side Effects",
    "Tumor Growth": "Disease Stage",
    "Tumor Shrinkage": "Disease Stage",
    "Stable Disease": "Disease Stage",
    "Liver": "Disease Sites/Locations",
    "Lymph Nodes": "Disease Sites/Locations",
    "Abdomen": "Disease Sites/Locations",
    "Chest": "Disease Sites/Locations",
    "Lungs": "Disease Sites/Locations",
    "Diaphragm": "Disease Sites/Locations",
    "Bones": "Disease Sites/Locations",
    "Brain": "Disease Sites/Locations",
    "Pancreas": "Disease Sites/Locations",
    "Gall Bladder": "Disease Sites/Locations",
    "Portal Vein": "Disease Sites/Locations",
    "Ovaries": "Disease Sites/Locations",
    "Kidney": "Disease Sites/Locations",
    "Bladder": "Disease Sites/Locations",
    "Stomach": "Disease Sites/Locations",
    "Spleen": "Disease Sites/Locations",
    "Stage I": "Disease Stage",
    "Stage II": "Disease Stage",
    "Stage III": "Disease Stage",
    "Stage IV": "Disease Stage"
});